#PATHS

RAW_DATA_DIR : 'data/raw/'
PROC_DATA_DIR : 'data/processed/'
INTERIM_DATA_DIR : 'data/interim/'
VALID_ACTIONS : {
# 'breakout' : [1, 3, 4],
'freeway' : [2, 5],
# 'alien' : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
# 'asterix' : [2, 3, 4, 5, 6, 7, 8, 9],
# 'bank_heist' : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
# 'berzerk' : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
# 'centipede' : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
# 'demon_attack' : [1, 3, 4, 11, 12],
# 'enduro' : [1, 3, 4, 5, 8, 9, 11, 12],
# 'frostbite' : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
# 'hero' : [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 0, 11, 12, 13, 14, 15, 16, 17],
# 'montezuma_revenge' : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
# 'ms_pacman' : [2, 3, 4, 5, 6, 7, 8, 9],
# 'name_this_game' : [1, 3, 4, 11, 12],
# 'phoenix' : [1, 3, 4, 5, 11, 12, 13],
# 'riverraid' : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
# 'road_runner' : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
# 'seaquest' : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
# 'venture' : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
# 'space_invaders' : [1, 3, 4, 11, 12],

}
MODEL_SAVE_DIR : 'models_/'
RUNS_DIR : 'runs/'
VIS_PREDS_DIR : 'data/vis/'
CMP_FMT : '.tar.bz2'
HDF_CMP_TYPE : 'gzip'
HDF_CMP_LEVEL : null
OVERWRITE_INTERIM_GAZE : False
STACK_SIZE : 4
BATCH_SIZE : 32
DATA_TYPES : ['frames', 'actions', 'gazes', 'gazes_fused_noop']